import type { Metadata } from "next"
import { Libre_Bodoni, Nunito_Sans } from "next/font/google"
import "./globals.css"

const newsReader = Libre_Bodoni({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
})

const newsReader2 = Nunito_Sans({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-theme="light" className={`${newsReader.variable} ${newsReader2.variable}`}>
      <body className="font-body antialiased">
        {children}
      </body>
    </html>
  )
}
