import type { Metadata } from "next"
import { Libre_Bodoni } from "next/font/google"
import "./globals.css"
import Footer from "@/app/components/Footer"
import Navigation from "@/app/components/Navbar"
const newsReader = Libre_Bodoni({
  variable: "--font-news-reader",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${newsReader.className} antialiased`} >
        <main>
          <Navigation />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
