import type { Metadata } from "next"
import { Libre_Bodoni, Afacad } from "next/font/google"
import "./globals.css"
import Footer from "@/app/components/Footer"
import Navigation from "@/app/components/Navbar"

const headerFont = Libre_Bodoni({
  weight: ["400", "600", "700"],
})

const bodyFont = Afacad({
  weight: ["400", "600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <main className="bg-[url('https://images.unsplash.com/photo-1578911373434-0cb395d2cbfb?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D')] bg-fixed bg-cover bg-center bg-black/70 bg-blend-multiply px-20 pt-[100px]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
